# Generated by Django 5.2.10 on 2026-02-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Слаг')),
            ],
        ),
    ]
