# Generated by Django 5.2.10 on 2026-02-04 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_date', models.DateField(verbose_name='Дата создание')),
                ('country', models.CharField(blank=True, null=True, verbose_name='Страна')),
                ('directed_by', models.CharField(verbose_name='Режисер')),
                ('age_rating', models.CharField(blank=True, null=True, verbose_name='Возраст')),
                ('raiting', models.PositiveIntegerField(default=5, verbose_name='Рейтинг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie/images/', verbose_name='Картинка')),
                ('trailir_video', models.FileField(blank=True, null=True, upload_to='movie/videos/', verbose_name='Видео Трейлер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
