# Generated by Django 6.0.2 on 2026-03-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_genre_movie_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-id',), 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
